# PyTorch
---

### [1] Tensor 생성
---

In [1]:
import torch

In [3]:
# PyTorch 버전 확인
torch.__version__

'1.12.1'

In [6]:
## [기본] tensor(data)
t1=torch.tensor([1, 2, 3], dtype=torch.int32)

In [7]:
type(t1), t1.shape, t1.dtype, t1.device

(torch.Tensor, torch.Size([3]), torch.int32, device(type='cpu'))

In [10]:
t2=torch.tensor([1., 2, 3])

In [11]:
# dtype 디폴트는 int64
type(t2), t2.shape, t2.dtype, t2.device

(torch.Tensor, torch.Size([3]), torch.float32, device(type='cpu'))

In [14]:
t3=torch.tensor([[1., 2, 3], [1, 2, 2]])

In [15]:
type(t3), t3.shape, t3.dtype, t3.device

(torch.Tensor, torch.Size([2, 3]), torch.float32, device(type='cpu'))

In [16]:
t4=torch.ones(size=(10, ))
t4

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
type(t4), t4.shape, t4.dtype, t4.device

(torch.Tensor, torch.Size([10]), torch.float32, device(type='cpu'))

In [18]:
t5=torch.zeros(size=(10, ))
t5

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
type(t5), t5.shape, t5.dtype, t5.device

(torch.Tensor, torch.Size([10]), torch.float32, device(type='cpu'))

In [20]:
# t3와 형태는 같게, 안에 원소는 1로 채우기 / zeros_like도 있음
t6=torch.ones_like(t3)
t6

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [21]:
torch.rand_like(t3)

tensor([[0.1938, 0.9433, 0.8381],
        [0.4893, 0.8713, 0.9628]])

## Indexing & Slicing

In [22]:
t3

tensor([[1., 2., 3.],
        [1., 2., 2.]])

In [26]:
t3.ndim, t3.shape

(2, torch.Size([2, 3]))

In [23]:
# 행 => [행인덱스]
t3[0]

tensor([1., 2., 3.])

In [24]:
t3[1]

tensor([1., 2., 2.])

In [28]:
# 열(columns) => [행, 열]
t3[:, 0], t3[0, 0]

(tensor([1., 1.]), tensor(1.))

In [29]:
t3.sum()

tensor(11.)

In [30]:
t3.mean()

tensor(1.8333)

In [31]:
t3.max()

tensor(3.)

In [33]:
tn=t3.numpy()
tn

array([[1., 2., 3.],
       [1., 2., 2.]], dtype=float32)

In [34]:
torch.cuda.is_available()

False